/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertirRouteImport } from './routes/convertir'
import { Route as IaRouteImport } from './routes/ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertirRoute = ConvertirRouteImport.update({
  id: '/convertir',
  path: '/convertir',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convertir': typeof ConvertirRoute
  '/ia': typeof IaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convertir': typeof ConvertirRoute
  '/ia': typeof IaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convertir': typeof ConvertirRoute
  '/ia': typeof IaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convertir' | '/ia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convertir' | '/ia'
  id: '__root__' | '/' | '/convertir' | '/ia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertirRoute: typeof ConvertirRoute
  IaRoute: typeof IaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convertir': {
      id: '/convertir'
      path: '/convertir'
      fullPath: '/convertir'
      preLoaderRoute: typeof ConvertirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertirRoute: ConvertirRoute,
  IaRoute: IaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
