/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertirRouteImport } from './routes/convertir'
import { Route as FlipbookRouteImport } from './routes/flipbook'
import { Route as IaRouteImport } from './routes/ia'
import { Route as OcrRouteImport } from './routes/ocr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertirRoute = ConvertirRouteImport.update({
  id: '/convertir',
  path: '/convertir',
  getParentRoute: () => rootRouteImport,
} as any)
const FlipbookRoute = FlipbookRouteImport.update({
  id: '/flipbook',
  path: '/flipbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convertir': typeof ConvertirRoute
  '/flipbook': typeof FlipbookRoute
  '/ia': typeof IaRoute
  '/ocr': typeof OcrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convertir': typeof ConvertirRoute
  '/flipbook': typeof FlipbookRoute
  '/ia': typeof IaRoute
  '/ocr': typeof OcrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convertir': typeof ConvertirRoute
  '/flipbook': typeof FlipbookRoute
  '/ia': typeof IaRoute
  '/ocr': typeof OcrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convertir' | '/flipbook' | '/ia' | '/ocr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convertir' | '/flipbook' | '/ia' | '/ocr'
  id: '__root__' | '/' | '/convertir' | '/flipbook' | '/ia' | '/ocr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertirRoute: typeof ConvertirRoute
  FlipbookRoute: typeof FlipbookRoute
  IaRoute: typeof IaRoute
  OcrRoute: typeof OcrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convertir': {
      id: '/convertir'
      path: '/convertir'
      fullPath: '/convertir'
      preLoaderRoute: typeof ConvertirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flipbook': {
      id: '/flipbook'
      path: '/flipbook'
      fullPath: '/flipbook'
      preLoaderRoute: typeof FlipbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertirRoute: ConvertirRoute,
  FlipbookRoute: FlipbookRoute,
  IaRoute: IaRoute,
  OcrRoute: OcrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
